# Azure DevOps settings:
ADOProjectName = "TF Real-World Examples Project"
ADOProjectDescription = "Example ADO project with real-world scenarios."
ADOProjectVisibility = "private"
ADOVersionControl = "Git"
ADOWorkItemTemplate = "Agile"
ADOFeature_Boards = "enabled"
ADOFeature_Repositories = "enabled"
ADOFeature_Pipelines = "enabled"
ADOFeature_TestPlans = "enabled"
ADOFeature_Artifacts = "enabled"
