trigger: none
  # branches:
  #   include:
  #     - master
  # paths:
  #   include:
  #     - /cleanup-hub.txt

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Terraform Sensitive Variables
  - name: StateFile
    value: deploy_hub.tfstate

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '0.12.28'
  - script: terraform version
    displayName: "Terraform Version"
  - script:  az login --service-principal -u $(application_id) -p $(SPNPwd) --tenant $(tenant_id)
    displayName: "Log Into Azure"
  - script: terraform init -backend-config=resource_group_name=$(StorageResourceGroup) -backend-config="storage_account_name=$(StorageAccountName)" -backend-config="container_name=$(ContainerName)" -backend-config="access_key=$(SASKey)" -backend-config="key=$(StateFile)"
    displayName: "Terraform Init"
    workingDirectory: $(System.DefaultWorkingDirectory)/Networking/Deployments/Network-Deployment/Hub-Deploy
  - script: terraform destroy -var="client_id=$(application_id)" -var="client_secret=$(SPNPwd)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)" -var-file="Hub.tfvars" -auto-approve
    displayName: "Terraform Destroy"
    workingDirectory: $(System.DefaultWorkingDirectory)/Networking/Deployments/Network-Deployment/Hub-Deploy